### ISSUE TITLE
Show desktop option no longer available

### ISSUE THREAD

**Issue by somepaulo** [janxyz/custom-hot-corners#15]
The 'Show desktop' option has disappeared from the dropdown menus after the most recent update from extensions.gnome.org
Only the 'Toggle overview', 'Show applications' and 'Run command' options are available.
Using Arch with Gnome Shell 3.34.2
Can't grab a screenshot with the dropdown open, sorry.

**Comment by janxyz** [comment]
I removed the 'Show desktop' function. I disliked it because it depended on wmctrl being installed. It's easy to recreate with a shell script:

    #!/usr/bin/env bash
    if wmctrl -m | grep -q -e "mode: OFF" -e "mode: N/A"; then
        wmctrl -k on;
    else
        wmctrl -k off;
    fi

**Comment by pvianag** [comment]
> I removed the 'Show desktop' function. I disliked it because it depended on wmctrl being installed. It's easy to recreate with a shell script:
> 
> ```
> #!/usr/bin/env bash
> if wmctrl -m | grep -q -e "mode: OFF" -e "mode: N/A"; then
>     wmctrl -k on;
> else
>     wmctrl -k off;
> fi
> ```

Perhaps you could recover the functionality and show a warning when this option is chosen.
Personally I use your great extension mainly because of the show-desktop function. Others like show activities are accesible easy by the super button (avoiding double keystrokes).

Thank you so much and congratulations for your work!

**Comment by janxyz** [comment]
Alright, I put the show desktop option back in in the newest version.
